name: Update YouTube Videos JSON

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  update-videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with write permissions
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important for push with GITHUB_TOKEN

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install xml2js

      - name: Fetch latest videos and write JSON
        run: node tools/fetch-videos.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/videos.json
          git diff --cached --quiet || git commit -m "ci: update videos.json"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
