name: Update Folder Structure

on:
  push:
    paths:
      - '**'
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run folder structure script
      run: |
        node tools/generate-structure.js

    - name: Commit folder structure
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "ci: update project folder structure"
        file_pattern: 'project-structure.md'
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: thelonewolf39 <117017247+thelonewolf39@users.noreply.github.com>
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
