name: Update Latest YouTube Video

on:
  workflow_dispatch:   # Manual trigger
  schedule:
    - cron: '0 * * * *'  # (Optional) every hour

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run YouTube fetch script
        run: node tools/fetch-videos.js

      - name: Commit and push updated JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: update latest YouTube video JSON'
          branch: master   # Change if your default branch is different
