name: Update YouTube Videos JSON

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install xml2js

      - name: Run fetch-videos script
        run: node tools/fetch-videos.js

      - name: Commit and push JSON updates
  uses: stefanzweifel/git-auto-commit-action@v5
  with:
    commit_message: 'ci: update latest videos JSON'
    branch: master
    file_pattern: 'data/*.json'
    commit_user_name: github-actions[bot]
    commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
    commit_author: 'thelonewolf39 <117017247+thelonewolf39@users.noreply.github.com>'
  env:
    GIT_AUTHOR_NAME: github-actions[bot]
    GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
